services:
  - type: web
    name: rag-torre-investimentos
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python simple_server.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: OPENAI_API_KEY
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
